<div class="wrap">

    <div id="responsive_menu_pro_version">
        <?php _e('Version'); ?> <?php echo ResponsiveMenuPro_Registry::get('config', 'current_version'); ?>                 
    </div>

    <form action="" method="post" enctype="multipart/form-data">

    <input 
        type="submit" 
        class="button button-primary" 
        name="responsive_menu_pro_submit" 
        value="<?php _e('Update Responsive Menu Options', 'responsive-menu-pro'); ?>"
        style="display: none;"
        />
        
        <h2><?php _e( 'Responsive Menu Pro Options', 'responsive-menu-pro' ); ?></h2>

        <?php
        if ($status = ResponsiveMenuPro_Status::get())
            echo self::statusBar($status);
        ?>

        <nav class="menu-tabs">
            <ul class="nav nav-tabs">
                <li class="tab active" data-show-tab=".setting">Setting</li>							
                <li class="tab" data-show-tab=".look-and-feel">Look & Feel</li>
                <li class="tab" data-show-tab=".advanced-setting">Advanced Setting</li>
                <li class="tab" data-show-tab=".import-export">Import/Export</li>
                <li class="tab" data-show-tab=".single-menu">Single Menu</li>
                <li class="tab" data-show-tab=".themes">Header Bar & Themes</li>                
                <li class="tab" data-show-tab=".custom-css">Custom CSS/HTML</li>				
            </ul>	
        </nav>	

        <div class="setting">
            <h3><?php _e('Meta Tag Check', 'responsive-menu-pro'); ?></h3>

            <table>
				<tr>
                    <td>
                        <h4><?php _e('Recommended Metaport Tag', 'responsive-menu-pro'); ?></h4>
                    </td>
                </tr>
                <tr>
                    <td>

                        &lt;meta name='viewport' content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' /&gt;
                    </td>
                </tr>
                <tr>
                    <td>                            
                        <h4 class="divider">
                            <?php _e('Note', 'responsive-menu-pro'); ?>: 
                            <?php _e('This is only a reference guide and yours may vary slightly', 'responsive-menu-pro'); ?>.
                        </h4>
                    </td>
                </tr>
            </table>

            <h3><?php _e('Transient Caching', 'responsive-menu-pro'); ?></h3>

            <table>

                <tr>
                    <td>
                        <h4>
                            <?php _e('Turn on transient caching', 'responsive-menu-pro'); ?>
                        </h4> 
                        <h5>
                            <?php _e('Transient caching will save you ~80% on load times, however please note that this will break active links etc.', 'responsive-menu-pro'); ?>
                        </h5> 

                        <input 
                            type="checkbox" 
                            name="use_transient_caching" 
                            id="use_transient_caching"
                            value="use_transient_caching"
                            <?php echo isset($data['use_transient_caching']) && $data['use_transient_caching'] == 'use_transient_caching' ? ' checked="checked" ' : ''; ?>
                            />

                    </td>
                </tr>
            </table>

            <h3><?php _e('Shortcode Support', 'responsive-menu-pro'); ?></h3>

            <table>
                <tr>
                    <td>

                        <table class='inner-table'>
                            <tr>
                                <td>
                                    <h4><?php _e('Click to use shortcode', 'responsive-menu-pro'); ?></h4> 

                                    <h5><?php _e('Tick if you would like to use a shortcode instead of the default behaviour', 'responsive-menu-pro'); ?></h5>

                                    <input 
                                        type="checkbox" 
                                        name="use_shortcode"
                                        value="use_shortcode"
                                        <?php echo isset( $data['use_shortcode']) && $data['use_shortcode'] == 'use_shortcode' ? ' checked="checked" ' : ''; ?>
                                        /> [responsive_menu_pro]
                                    <br /><br />
                                </td>        
                            </tr>  
                            <tr>
                                <td colspan="2">
                                    <?php _e("For a list of available shortcode options with explanations please visit the following page:", 'responsive-menu-pro'); ?> 
                                    <br /><br />
                                    <a target="_blank" href="http://responsive.menu/faq/shortcode/options/">
                                        <?php _e("Shortcode Options"); ?>
                                    </a>
                                </td>
                            </tr>
                        </table>
                    </td>
                    <td>

                        <h4><?php _e("Available Shortcode Options/Values"); ?></h4>

                        <table>
                            <tr>
                                <td><strong><?php _e("Option"); ?></strong></td>
                                <td><strong><?php _e("Values"); ?></strong></td>
                            </tr>

                            <?php
                            if (ResponsiveMenuPro::hasMenus()) :

                                $i = 0;

                                foreach ($menus = ResponsiveMenuPro::getMenus() as $menu) :

                                    $opt = $i == 0 ? 'menu' : '';

                                    echo '<tr><td>' . $opt . '</td><td>' . $menu->slug . '</td></tr>';

                                    $i++;

                                endforeach;

                                echo '<tr><td colspan="2"><br /><em>e.g - [responsive_menu_pro menu="' . $menus[0]->slug . '"]</em></td></tr>';

                            else :

                                echo '<tr><td colspan="2">' . _e("Sorry, there are no available options") . '</td></tr>';

                            endif;
                            ?>
                            <tr>
                                <td><strong><?php _e("Option"); ?></strong></td>
                                <td><strong><?php _e("Example Value"); ?></strong></td>
                            </tr>
                            <tr>
                                <td>title</td>
                                <td>Título</td>
                            </tr>
                            <tr>
                                <td>title_link</td>
                                <td>http://mipagina.es</td>
                            </tr>
                            <tr>
                                <td>title_open</td>
                                <td>_blank</td>
                            </tr>
                            <tr>
                                <td>title_img</td>
                                <td>http://example.com/title-img-2.jpg</td>
                            </tr>
                            <tr>
                                <td>html</td>
                                <td>&lt;a href='http://www.example.com'&gt;Example&lt;/a&gt;</td>
                            </tr>
                            <tr>
                                <td>html_loc</td>
                                <td>above</td>
                            </tr>
                            <tr>
                                <td>search_loc</td>
                                <td>below</td>
                            </tr>
                            <tr>
                                <td>btn_img</td>
                                <td>http://example.com/btn-img-2.jpg</td>
                            </tr>
                            <tr>
                                <td>btn_img_clicked</td>
                                <td>http://example.com/btn-img-clicked-2.jpg</td>
                            </tr>
                            <tr>
                                <td>btn_title</td>
                                <td>Menú</td>
                            </tr>
                            <tr>
                                <td>&nbsp;</td>
                                <td>&nbsp;</td>
                            </tr>
                            <tr>
                                <td colspan="2">
                                    <em><?php _e("e.g"); ?> - [responsive_menu_pro title="Título" title_link="http://mipagina.es"]</em>
                                </td>
                            </tr>
                        </table>

                    </td>
                </tr>


            </table>
            
            <h3><?php _e( 'Mobile devices', 'responsive-menu-pro' ); ?></h3>
            
            <table>
                <tr>
                    <td>
                        <h4>
                            <?php _e( 'Only use Responsive Menu on mobile devices', 'responsive-menu-pro'); ?>
                        </h4> 
                        <h5>
                            <?php _e('This will ignore all breakpoint width settings and show the menu only on mobile devices using the wp_is_mobile() function', 'responsive-menu-pro'); ?>
                        </h5> 

                        <input 
                            type="checkbox" 
                            name="use_only_on_mobile" 
                            value="use_only_on_mobile"
                            <?php echo isset( $data['use_only_on_mobile'] ) && $data['use_only_on_mobile'] == 'use_only_on_mobile' ? ' checked="checked" ' : ''; ?>
                            />

                    </td>
                </tr>
            </table>
            
        </div>

        <div class="look-and-feel">
            <h3><?php _e('Click Button Settings', 'responsive-menu-pro'); ?></h3>

            <table>

                <tr>
                    <td>
                        <h4><?php _e('Click Button Title', 'responsive-menu-pro'); ?></h4> 

                        <h5><?php _e('This is the title under the 3 lines of the click button', 'responsive-menu-pro'); ?></h5>

                        <input 
                            type="text" 
                            name="button_text" 
                            value="<?php echo isset($data['button_text']) ? $data['button_text'] : ''; ?>" 
                            />
                    </td>
                    <td>

                        <h4><?php _e('Click Button Image', 'responsive-menu-pro'); ?></h4> 

                        <h5><?php _e('This is the click button that replaces the 3 lines. If empty, the 3 lines will be used', 'responsive-menu-pro'); ?></h5>

                        <input 
                            type="text" 
                            id="button_image" 
                            name="button_image" 
                            value="<?php echo isset($data['button_image']) ? $data['button_image'] : ''; ?>" 
                            />

                        <input 
                            type="button"
                            value="<?php _e('Upload Image', 'responsive-menu-pro'); ?>" 
                            class="button RMImageButton" 
                            for="button_image"
                            />

                    </td>
                </tr>
                <tr>
                    <td>
                        <h4><?php _e('Change click menu to an X on click', 'responsive-menu-pro'); ?></h4> 

                        <h5>
                            <?php _e('Tick this if you would like the 3 lines to turn into an x once clicked', 'responsive-menu-pro'); ?>. 
                        </h5>
                        <input 
                            type="checkbox" 
                            name="use_x" 
                            id="use_x"
                            value="rmx"
                            <?php echo $data['use_x'] == 'rmx' ? ' checked="checked" ' : ''; ?>
                            />
                    </td>
                    <td>

                        <h4><?php _e('Click Button Image When Clicked', 'responsive-menu-pro'); ?></h4> 

                        <h5><?php _e('This is the click button image that replaces the 3 lines when clicked. If empty, the 3 lines will be used', 'responsive-menu-pro'); ?></h5>

                        <input 
                            type="text" 
                            id="button_image_clicked" 
                            name="button_image_clicked" 
                            value="<?php echo isset($data['button_image_clicked']) ? $data['button_image_clicked'] : ''; ?>" 
                            />

                        <input 
                            type="button"
                            value="<?php _e('Upload Image', 'responsive-menu-pro'); ?>" 
                            class="button RMImageButton" 
                            for="button_image_clicked"
                            />

                    </td>
                </tr>


                <tr>
                    <td>

                        <h4><?php _e('Fixed Positioning', 'responsive-menu-pro'); ?></h4> 

                        <h5><?php _e('Tick this if you would like the click button to remain in the same place when scrolling', 'responsive-menu-pro'); ?>.</h5>

                        <input 
                            type="checkbox" 
                            name="is_fixed" 
                            id="is_fixed"
                            value="fixed"
                            <?php echo $data['is_fixed'] == 'fixed' ? ' checked="checked" ' : ''; ?>
                            />

                    </td>
                    <td>

                        <h4><?php _e('Click Trigger', 'responsive-menu-pro'); ?></h4> 

                        <h5><?php _e('You can set a custom ID or class for custom triggers here if you wish.', 'responsive-menu-pro'); ?>.</h5>

                        <input 
                            type="text" 
                            name="trigger" 
                            id="trigger"
                            value="<?php echo isset($data['trigger']) ? $data['trigger'] : ResponsiveMenuPro_Registry::get('defaults', 'trigger'); ?>"
                            />

                    </td>
                </tr>
            </table>

            <h3><?php _e('Click Button Size Settings', 'responsive-menu-pro'); ?></h3>

            <table>
                <tr>
                    <td>

                        <h4><?php _e('Width', 'responsive-menu-pro'); ?></h4> 

                        <h5><?php _e('This is the width of the individual 3 lines', 'responsive-menu-pro'); ?></h5>

                        <input 
                            class="numberInput" 
                            type="text" 
                            name="line_width" 
                            value="<?php echo isset($data['line_width']) ? $data['line_width'] : ''; ?>" 
                            /> <?php _e('px', 'responsive-menu-pro'); ?>

                    </td>
                    <td>

                        <h4><?php _e('Height', 'responsive-menu-pro'); ?></h4> 

                        <h5><?php _e('This is the height of the individual 3 lines', 'responsive-menu-pro'); ?></h5>

                        <input 
                            class="numberInput" 
                            type="text" 
                            name="line_height" 
                            value="<?php echo isset($data['line_height']) ? $data['line_height'] : ''; ?>" 
                            /> <?php _e('px', 'responsive-menu-pro'); ?>

                    </td>
                </tr>
                <tr>
                    <td>

                        <h4><?php _e('Margin', 'responsive-menu-pro'); ?></h4> 

                        <h5><?php _e('This is the margin between the individual 3 lines', 'responsive-menu-pro'); ?></h5>

                        <input 
                            class="numberInput" 
                            type="text" 
                            name="line_margin" 
                            value="<?php echo isset($data['line_margin']) ? $data['line_margin'] : ''; ?>" 
                            /> <?php _e('px', 'responsive-menu-pro'); ?>

                    </td>
                    <td>

                        <h4></h4> 

                        <h5></h5>

                    </td>
                </tr>
            </table>

            <h3><?php _e('Click Button Location Settings', 'responsive-menu-pro'); ?></h3>

            <table>
                <tr>
                    <td>

                        <h4><?php _e('Top', 'responsive-menu-pro'); ?></h4> 

                        <h5><?php _e('This is the distance from the top of the page in px that the click button will be displayed', 'responsive-menu-pro'); ?></h5>

                        <input 
                            class="numberInput" 
                            type="text" 
                            name="top" 
                            value="<?php echo isset($data['top']) ? $data['top'] : ''; ?>" 
                            /> <?php _e('px', 'responsive-menu-pro'); ?>

                    </td>
                    <td>

                        <h4><?php _e('Left/Right Distance', 'responsive-menu-pro'); ?></h4> 

                        <h5><?php _e('This is the distance from the right/left of the page (as defined below) in % that the menu will be displayed', 'responsive-menu-pro'); ?></h5>

                        <input 
                            class="numberInput" 
                            type="text" 
                            name="right" 
                            value="<?php echo isset($data['right']) ? $data['right'] : ''; ?>" 
                            /> %

                    </td>
                </tr>
                <tr>
                    <td>

                        <h4><?php _e('Left/Right', 'responsive-menu-pro'); ?></h4> 

                        <h5><?php _e('This defines whether the menu button is shown as a percentage from the left or right', 'responsive-menu-pro'); ?></h5>

                        <select name="location">

                            <option 
                                value="left"
                                <?php echo 'left' == $data['location'] ? 'selected="selected"' : ''; ?>>
                                Left
                            </option>

                            <option 
                                value="right"
                                <?php echo 'right' == $data['location'] ? 'selected="selected"' : ''; ?>>
                                Right
                            </option>

                        </select>

                    </td>
                    <td>

                        <h4></h4> 

                        <h5></h5>


                    </td>
                </tr>
            </table>

            <h3><?php _e('Menu Settings', 'responsive-menu-pro'); ?></h3>

            <table>

                <tr>
                    <td>

                        <h4><?php _e('Menu Title', 'responsive-menu-pro'); ?></h4> 

                        <h5><?php _e('This is the title at the top of the responsive menu', 'responsive-menu-pro'); ?></h5>

                        <input 
                            type="text" 
                            name="title" 
                            value="<?php echo isset($data['title']) ? $data['title'] : ''; ?>" 
                            />

                    </td>
                    <td>

                        <h4><?php _e('Menu Image', 'responsive-menu-pro'); ?></h4> 

                        <h5><?php _e('This is the image that sits next to the responsive menu title. The best size is 32px x 32px', 'responsive-menu-pro'); ?></h5>

                        <input 
                            type="text" 
                            id="title_image" 
                            name="title_image" 
                            value="<?php echo isset($data['title_image']) ? $data['title_image'] : ''; ?>" 
                            />

                        <input 
                            type="button" 
                            value="<?php _e('Upload Image', 'responsive-menu-pro'); ?>" 
                            class="button RMImageButton" 
                            for="title_image"
                            />

                    </td>
                </tr>

                <tr>
                    <td>
                        <h4><?php _e('Choose Menu To Responsify', 'responsive-menu-pro'); ?></h4> 

                        <h5><?php _e('This is the menu that will be used responsively', 'responsive-menu-pro'); ?>.</h5>

                        <?php if (ResponsiveMenuPro::hasMenus()) : ?>

                            <select name="menu">

                                <?php foreach (ResponsiveMenuPro::getMenus() as $menu) : ?>

                                    <option 
                                        value="<?php echo $menu->slug; ?>"
                                        <?php echo $menu->slug == $data['menu'] ? 'selected="selected">' : '>'; ?>
                                        <?php echo $menu->name; ?>
                                </option>

                            <?php endforeach; ?>

                        </select>

                    <?php else : ?>

                        <span style="color: red;"><?php _e("You haven't set up any site menus yet", "responsive-menu-pro"); ?>.</span>

                    <?php endif; ?>  



                </td>
                <td>

                    <h4><?php _e('Slide Side', 'responsive-menu-pro'); ?></h4> 

                    <h5><?php _e('This is the side of the screen from which the menu will slide', 'responsive-menu-pro'); ?></h5>

                    <select name="slide_side">

                        <option 
                            value="left"
                            <?php echo isset($data['slide_side']) && $data['slide_side'] == 'left' ? 'selected="selected"' : ''; ?>>
                                <?php _e('Left', 'responsive-menu-pro'); ?>
                        </option>

                        <option 
                            value="right"
                            <?php echo isset($data['slide_side']) && $data['slide_side'] == 'right' ? 'selected="selected"' : ''; ?>>
                                <?php _e('Right', 'responsive-menu-pro'); ?>
                        </option>

                        <option 
                            value="top"
                            <?php echo isset($data['slide_side']) && $data['slide_side'] == 'top' ? 'selected="selected"' : ''; ?>>
                                <?php _e('Top', 'responsive-menu-pro'); ?>
                        </option>

                        <option 
                            value="bottom"
                            <?php echo isset($data['slide_side']) && $data['slide_side'] == 'bottom' ? 'selected="selected"' : ''; ?>>
                                <?php _e('Bottom', 'responsive-menu-pro'); ?>
                        </option>

                    </select>     


                </td>
            </tr>
            <tr>
                <td>

                    <?php // Choose Theme Location Menu add by mkdgs   ?>  

                    <h4><?php _e('Choose Theme Location Menu To Responsify', 'responsive-menu-pro'); ?></h4> 

                    <h5><?php _e('The menu assigned to this theme location (registered with register_nav_menu) will be used for displaying the responsive menu (useful if you use a plugin like polylang)', 'responsive-menu-pro'); ?>.</h5>

                    <?php if ($MenusLocations = ResponsiveMenuPro::getMenusLocations()) : ?>

                        <select name="theme_location">                                        
                            <?php foreach ($MenusLocations as $location) : ?>

                                <option 
                                    value="<?php echo $location->location; ?>"
                                    <?php echo $location->location == $data['theme_location'] ? 'selected="selected"' : ''; ?>>
                                        <?php echo $location->description; ?>
                                </option>

                            <?php endforeach; ?>

                            <option 
                                value=""
                                <?php echo ( empty($data['theme_location']) ) ? 'selected="selected"' : ''; ?>  
                                >
                                    <?php echo _e('None', 'responsive-menu-pro'); ?>
                            </option>

                        </select>

                    <?php else : ?>

                        <span style="color: red;"><?php _e("You haven't set up any menus location yet", "responsive-menu-pro"); ?>.</span>

                    <?php endif; ?>

                </td>
                <td>
                   <h4><?php _e('Set auto height on menu', 'responsive-menu-pro'); ?></h4> 

                    <h5><?php _e('Tick this if you would like the menu to have the height be automatically sized', 'responsive-menu-pro'); ?></h5>

                    <input 
                        type="checkbox" 
                        name="set_auto_menu_height" 
                        value="checked"
                        <?php echo $data['set_auto_menu_height'] == 'checked' ? ' checked="checked" ' : ''; ?>
                        />
                </td>
            </tr>
            <tr>
                <td>
                    <h4><?php _e('Menu Title Link', 'responsive-menu-pro'); ?></h4> 

                    <h5><?php _e('This is the link location for the title', 'responsive-menu-pro'); ?></h5>

                    <input 
                        type="text" 
                        name="title_link" 
                        value="<?php echo isset($data['title_link']) ? $data['title_link'] : ''; ?>" 
                        />
                </td>
                <td>

                    <h4><?php _e('Menu Title Link Location', 'responsive-menu-pro'); ?></h4> 

                    <h5><?php _e('This is where your title page will be opened once clicked', 'responsive-menu-pro'); ?></h5>

                    <select name="title_target">

                        <option 
                            value="_blank"
                            <?php echo isset($data['title_target']) && $data['title_target'] == '_blank' ? 'selected="selected"' : ''; ?>>
                                <?php _e('New Tab', 'responsive-menu-pro'); ?>
                        </option>

                        <option 
                            value="_self"
                            <?php echo isset($data['title_target']) && $data['title_target'] == '_self' ? 'selected="selected"' : ''; ?>>
                                <?php _e('Same Page', 'responsive-menu-pro'); ?>
                        </option>

                        <option 
                            value="_parent"
                            <?php echo isset($data['title_target']) && $data['title_target'] == '_parent' ? 'selected="selected"' : ''; ?>>
                                <?php _e('Parent Page', 'responsive-menu-pro'); ?>
                        </option>

                        <option 
                            value="_top"
                            <?php echo isset($data['title_target']) && $data['title_target'] == '_top' ? 'selected="selected"' : ''; ?>>
                                <?php _e('Full Window Body', 'responsive-menu-pro'); ?>
                        </option>

                    </select>   

                </td>
            </tr>
        </table>



        <h3><?php _e('Sub Menu Arrow Settings', 'responsive-menu-pro'); ?></h3>

        <table>
            <tr>
                <td>

                    <h4><?php _e('Active Geometric Shape', 'responsive-menu-pro'); ?></h4> 

                    <input 
                        type="text" 
                        name="arrow_shape_active" 
                        value="<?php echo isset($data['arrow_shape_active']) ? json_decode($data['arrow_shape_active']) : ''; ?>" 
                        />

                </td>
                <td>

                    <h4><?php _e('Inactive Geometric Shape', 'responsive-menu-pro'); ?></h4> 

                    <input 
                        type="text" 
                        name="arrow_shape_inactive" 
                        value="<?php echo isset($data['arrow_shape_inactive']) ? json_decode($data['arrow_shape_inactive']) : ''; ?>" 
                        />

                </td>
            </tr>

            <tr>
                <td colspan="2">
                    <h4><?php _e('You can find a list of Geometric HTML shape codes below', 'responsive-menu-pro'); ?>:</h4> 
                    <a target="_blank" href="http://responsive.menu/html-geometric-shapes">http://responsive.menu/html-geometric-shapes</a>
                </td>
           </tr>
            <tr>
                <td>

                    <h4><?php _e('Active Image', 'responsive-menu-pro'); ?></h4> 

                    <input 
                        type="text" 
                        id="array_image_active" 
                        name="array_image_active" 
                        value="<?php echo isset($data['array_image_active']) ? $data['array_image_active'] : ''; ?>" 
                        />

                    <input 
                        type="button"
                        value="<?php _e('Upload Image', 'responsive-menu-pro'); ?>" 
                        class="button RMImageButton" 
                        for="array_image_active"
                        />

                </td>
                <td>

                    <h4><?php _e('Inactive Image', 'responsive-menu-pro'); ?></h4> 

                    <input 
                        type="text"
                        name="arrow_image_inactive" 
                        value="<?php echo isset($data['arrow_image_inactive']) ? $data['arrow_image_inactive'] : ''; ?>" 
                        />

                    <input 
                        type="button"
                        value="<?php _e('Upload Image', 'responsive-menu-pro'); ?>" 
                        class="button RMImageButton" 
                        for="arrow_image_inactive"
                        />

                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <h4 class="divider">
                        <?php _e('Note'); ?>: 
                        <?php _e('Images have preference over shapes, to use HTML shapes please leave the image field blank', 'responsive-menu-pro'); ?>.
                    </h4>
                </td>
            </tr>

        </table>

        <h3><?php _e('Colour Settings', 'responsive-menu-pro'); ?></h3>

        <h4 class="divider"><?php _e('Background Colours', 'responsive-menu-pro'); ?></h4>

        <h5 class="sub-divider"><?php _e('Click Button', 'responsive-menu-pro'); ?></h5>

        <table>
            <tr>
                <td>

                    <h4><?php _e('Click Button Line & Text Colour', 'responsive-menu-pro'); ?></h4> 

                    <h5><?php _e('This is the colour of the 3 lines and text for the click button', 'responsive-menu-pro'); ?></h5>

                    <input 
                        type="text" 
                        name="button_line_colour"
                        class="colourPicker" 
                        value="<?php echo isset($data['button_line_colour']) ? $data['button_line_colour'] : ''; ?>" 
                        />

                </td>
                <td>

                    <h4><?php _e('Click Button Background Colour', 'responsive-menu-pro'); ?></h4> 

                    <h5><?php _e('This is the background colour of the 3 lines container', 'responsive-menu-pro'); ?></h5>

                    <input 
                        type="text" 
                        name="button_background_colour" 
                        class="colourPicker" 
                        value="<?php echo isset($data['button_background_colour']) ? $data['button_background_colour'] : ''; ?>" 
                        />

                </td>
            </tr>
            <tr>
                <td>

                    <h4><?php _e('Click Button Background Transparent', 'responsive-menu-pro'); ?></h4> 

                    <h5><?php _e('Tick this if you would like a transparent background on the click button', 'responsive-menu-pro'); ?></h5>

                    <input 
                        type="checkbox" 
                        name="is_button_background_transparent" 
                        value="is_button_background_transparent"
                        <?php echo $data['is_button_background_transparent'] == 'is_button_background_transparent' ? ' checked="checked" ' : ''; ?>
                        />

                </td>
            <tr>
                <td>
                </td>
            </tr>

        </table>



        <h5 class="sub-divider"><?php _e('Main Menu', 'responsive-menu-pro'); ?></h5>



        <table>
            <tr>
                <td>

                    <h4><?php _e('Link Background Colour', 'responsive-menu-pro'); ?></h4> 

                    <h5><?php _e('This is the background colour of the menu links', 'responsive-menu-pro'); ?></h5>

                    <input 
                        type="text" 
                        name="background_colour" 
                        class="colourPicker" 
                        value="<?php echo isset($data['background_colour']) ? $data['background_colour'] : ''; ?>" 
                        />

                </td>
                <td>

                    <h4><?php _e('Link Background Hover Colour', 'responsive-menu-pro'); ?></h4> 

                    <h5><?php _e('This is the hover background colour of the menu links', 'responsive-menu-pro'); ?></h5>

                    <input 
                        type="text" 
                        name="background_colour_hover"
                        class="colourPicker" 
                        value="<?php echo isset($data['background_colour_hover']) ? $data['background_colour_hover'] : ''; ?>" 
                        />

                </td>
            </tr>
            <tr>
                <td>

                    <h4><?php _e('Menu Link Border Colour', 'responsive-menu-pro'); ?></h4> 

                    <h5><?php _e('This is the border colour of the menu links', 'responsive-menu-pro'); ?></h5>

                    <input 
                        type="text" 
                        name="link_border_colour" 
                        class="colourPicker" 
                        value="<?php echo isset($data['link_border_colour']) ? $data['link_border_colour'] : ''; ?>" 
                        />

                </td>
                <td>

                    <h4><?php _e('Title Background Colour', 'responsive-menu-pro'); ?></h4> 

                    <h5><?php _e('This is the background colour of the menu title', 'responsive-menu-pro'); ?></h5>

                    <input 
                        type="text" 
                        name="title_background_colour"
                        class="colourPicker" 
                        value="<?php echo isset($data['title_background_colour']) ? $data['title_background_colour'] : ''; ?>" 
                        />

                </td>
            </tr>
            <tr>
                <td>

                    <h4><?php _e('Current Page Link Background Colour', 'responsive-menu-pro'); ?></h4> 

                    <h5><?php _e('This is the background colour of the current page link', 'responsive-menu-pro'); ?></h5>

                    <input 
                        type="text" 
                        name="current_page_link_background" 
                        class="colourPicker" 
                        value="<?php echo isset($data['current_page_link_background']) ? $data['current_page_link_background'] : ''; ?>" 
                        />

                </td>
                <td>

                    <h4><?php _e('Current Page Link Background Hover Colour', 'responsive-menu-pro'); ?></h4> 

                    <h5><?php _e('This is the hover background colour of the current page link', 'responsive-menu-pro'); ?></h5>

                    <input 
                        type="text" 
                        name="current_background_hover" 
                        class="colourPicker" 
                        value="<?php echo isset($data['current_background_hover']) ? $data['current_background_hover'] : ''; ?>" 
                        />

                </td>
            </tr>
        </table>

        <h4 class="divider"><?php _e('Text Colours', 'responsive-menu-pro'); ?></h4>



        <table>
            <tr>

                <td>

                    <h4><?php _e('Menu Title Colour', 'responsive-menu-pro'); ?></h4> 

                    <h5><?php _e('This is the text colour of the menu title', 'responsive-menu-pro'); ?></h5>

                    <input 
                        type="text" 
                        name="title_colour" 
                        id="title_colour" 
                        class="colourPicker" 
                        value="<?php echo isset($data['title_colour']) ? $data['title_colour'] : ''; ?>" 
                        />

                </td>
                <td>

                    <h4><?php _e('Menu Title Hover Colour', 'responsive-menu-pro'); ?></h4> 

                    <h5><?php _e('This is the hover colour of the menu title', 'responsive-menu-pro'); ?></h5>

                    <input 
                        type="text" 
                        name="title_colour_hover" 
                        class="colourPicker" 
                        value="<?php echo isset($data['title_colour_hover']) ? $data['title_colour_hover'] : ''; ?>" 
                        />

                </td>
            </tr>
            <tr>
                <td>

                    <h4><?php _e('Menu Link Colour', 'responsive-menu-pro'); ?></h4> 

                    <h5><?php _e('This is the text colour of the menu links', 'responsive-menu-pro'); ?></h5>

                    <input 
                        type="text" 
                        name="text_colour" 
                        class="colourPicker" 
                        value="<?php echo isset($data['text_colour']) ? $data['text_colour'] : ''; ?>" 
                        />

                </td>
                <td>

                    <h4><?php _e('Menu Link Hover Colour', 'responsive-menu-pro'); ?></h4> 

                    <h5><?php _e('This is the text hover colour of the menu links', 'responsive-menu-pro'); ?></h5>

                    <input 
                        type="text" 
                        name="text_colour_hover" 
                        class="colourPicker" 
                        value="<?php echo isset($data['text_colour_hover']) ? $data['text_colour_hover'] : ''; ?>" 
                        />

                </td>
            </tr>

            <tr>
                <td>

                    <h4><?php _e('Current Page Link Colour', 'responsive-menu-pro'); ?></h4> 

                    <h5><?php _e('This is the text colour of the current page link', 'responsive-menu-pro'); ?></h5>

                    <input 
                        type="text" 
                        name="current_page_link_colour" 
                        class="colourPicker" 
                        value="<?php echo isset($data['current_page_link_colour']) ? $data['current_page_link_colour'] : ''; ?>" 
                        />

                </td>
                <td>

                    <h4><?php _e('Current Page Link Hover Colour', 'responsive-menu-pro'); ?></h4> 

                    <h5><?php _e('This is the text hover colour of the current page link', 'responsive-menu-pro'); ?></h5>

                    <input 
                        type="text" 
                        name="current_colour_hover" 
                        id="current_colour_hover" 
                        class="colourPicker" 
                        value="<?php echo isset($data['current_colour_hover']) ? $data['current_colour_hover'] : ''; ?>" 
                        />


                </td>
            </tr>
        </table>



        <h3><?php _e('Style Settings', 'responsive-menu-pro'); ?></h3>

        <table>

            <tr>
                <td>

                    <h4><?php _e('Font', 'responsive-menu-pro'); ?></h4> 

                    <h5><?php _e('Enter a font name below, if empty your default site font will be used', 'responsive-menu-pro'); ?></h5>

                    <input 
                        type="text" 
                        name="font" 
                        value="<?php echo isset($data['font']) ? $data['font'] : ''; ?>" 
                        />

                </td>
                <td>    

                    <h4><?php _e('Font Size', 'responsive-menu-pro'); ?></h4> 

                    <h5><?php _e('Enter a font size in pixels below', 'responsive-menu-pro'); ?>. <span class='default'><?php _e('default', 'responsive-menu-pro'); ?>: 13</span></h5>

                    <input 
                        type="text" 
                        name="link_text_size" 
                        class="numberInput" 
                        value="<?php echo isset($data['link_text_size']) ? $data['link_text_size'] : ''; ?>" 
                        /> <?php _e('px', 'responsive-menu-pro'); ?>

                </td>
            </tr>  

            <tr>
                <td>

                    <h4><?php _e('Click Button Font Size', 'responsive-menu-pro'); ?></h4> 

                    <h5><?php _e('Enter a click button font size in pixels below', 'responsive-menu-pro'); ?>. <span class='default'><?php _e('default', 'responsive-menu-pro'); ?>: 13</span></h5>

                    <input 
                        type="text" 
                        name="button_text_size" 
                        class="numberInput" 
                        value="<?php echo isset($data['button_text_size']) ? $data['button_text_size'] : ''; ?>" 
                        /> <?php _e('px', 'responsive-menu-pro'); ?>

                </td>
                <td>  

                    <h4><?php _e('Title Font Size', 'responsive-menu-pro'); ?></h4> 

                    <h5><?php _e('Enter a title font size in pixels below', 'responsive-menu-pro'); ?>. <span class='default'><?php _e('default', 'responsive-menu-pro'); ?>: 14</span></h5>

                    <input 
                        type="text" 
                        name="title_text_size" 
                        class="numberInput" 
                        value="<?php echo isset($data['title_text_size']) ? $data['title_text_size'] : ''; ?>" 
                        /> <?php _e('px', 'responsive-menu-pro'); ?>

                </td>
            </tr>    

            <tr>
                <td>

                    <h4><?php _e('Text Alignment', 'responsive-menu-pro'); ?></h4> 

                    <h5><?php _e('Enter a text alignment option below', 'responsive-menu-pro'); ?> <span class='default'><?php _e('default', 'responsive-menu-pro'); ?>: <?php _e('Left', 'responsive-menu-pro'); ?></span></h5>

                    <select name="text_align">

                        <option 
                            value="left"
                            <?php echo isset($data['text_align']) && 'overlay' == $data['text_align'] ? ' selected="selected " ' : ''; ?>>
                                <?php _e('Left', 'responsive-menu-pro'); ?>
                        </option>
                        <option 
                            value="center"
                            <?php echo isset($data['text_align']) && 'center' == $data['text_align'] ? ' selected="selected " ' : ''; ?>>
                                <?php _e('Centre', 'responsive-menu-pro'); ?>
                        </option>  
                        <option 
                            value="right"
                            <?php echo isset($data['text_align']) && 'right' == $data['text_align'] ? ' selected="selected " ' : ''; ?>>
                                <?php _e('Right', 'responsive-menu-pro'); ?>
                        </option> 

                    </select>

                </td>               
                <td>                    

                    <h4><?php _e('Links Height', 'responsive-menu-pro'); ?></h4> 

                    <h5><?php _e('Enter a link height size in pixels below', 'responsive-menu-pro'); ?>. <span class='default'><?php _e('default', 'responsive-menu-pro'); ?>: 20</span></h5>

                    <input 
                        type="text" 
                        name="link_height" 
                        class="numberInput" 
                        value="<?php echo isset($data['link_height']) ? $data['link_height'] : ''; ?>" 
                        /> <?php _e('px', 'responsive-menu-pro'); ?>

                </td>
            </tr>
        </table>

        <h4 class="divider">
            <strong><?php _e('Note'); ?>: </strong>
            <?php _e('Setting the below two values to the same number will give you a fixed width effect', 'responsive-menu-pro'); ?>
        </h4>



        <table>

            <tr>
                <td>                    

                    <h4><?php _e('Minimum Width', 'responsive-menu-pro'); ?></h4> 

                    <h5><?php _e('Enter a minimum menu width size in pixels below', 'responsive-menu-pro'); ?>.</h5>

                    <input 
                        type="text" 
                        name="min_width" 
                        class="numberInput" 
                        value="<?php echo isset($data['min_width']) ? $data['min_width'] : ''; ?>" 
                        /> <?php _e('px', 'responsive-menu-pro'); ?>

                </td>
                <td>                    

                    <h4><?php _e('Maximum Width', 'responsive-menu-pro'); ?></h4> 

                    <h5><?php _e('Enter a maximum menu width size in pixels below', 'responsive-menu-pro'); ?>.</h5>

                    <input 
                        type="text" 
                        name="max_width" 
                        class="numberInput" 
                        value="<?php echo isset($data['max_width']) ? $data['max_width'] : ''; ?>" 
                        /> <?php _e('px', 'responsive-menu-pro'); ?>

                </td>
            </tr>
        </table>



        <h3><?php _e('Animation Settings', 'responsive-menu-pro'); ?></h3>

        <table>
            <tr>
                <td>

                    <h4><?php _e('Slide Animation', 'responsive-menu-pro'); ?></h4> 

                    <h5><?php _e('Choose the type of animation applied to the menu', 'responsive-menu-pro'); ?></h5>

                    <select name="animation_type">

                        <option 
                            value="overlay"
                            <?php echo 'overlay' == $data['animation_type'] ? ' selected="selected " ' : ''; ?>>
                                <?php _e('Overlay', 'responsive-menu-pro'); ?>
                        </option>
                        <option 
                            value="push"
                            <?php echo 'push' == $data['animation_type'] ? ' selected="selected " ' : ''; ?>>
                                <?php _e('Push', 'responsive-menu-pro'); ?>
                        </option>      

                    </select>

                </td>
                <td>

                    <h4><?php _e('Page Wrappers CSS', 'responsive-menu-pro'); ?></h4> 

                    <h5><?php _e('This is the CSS of the wrapper you want to push when using the push animation', 'responsive-menu-pro'); ?> (<?php _e('e.g', 'responsive-menu-pro'); ?> - #pushWrapper)</h5>

                    <input 
                        type="text" 
                        name="push_animation_container_css" 
                        value="<?php echo isset($data['push_animation_container_css']) ? $data['push_animation_container_css'] : ''; ?>" 
                        />

                </td>
            </tr>

            <tr>
                <td>

                    <h4><?php _e('Animation Speed', 'responsive-menu-pro'); ?></h4> 

                    <h5><?php _e('Enter a speed in seconds below of the slide animation', 'responsive-menu-pro'); ?>. <span class="default"><?php _e('default', 'responsive-menu-pro'); ?>: 0.5</span></h5>

                    <input 
                        type="text" 
                        name="animation_speed" 
                        class="numberInput" 
                        value="<?php echo isset($data['animation_speed']) ? $data['animation_speed'] : ''; ?>" 
                        /> <?php _e('seconds', 'responsive-menu-pro'); ?>

                </td>
                <td>

                    <h4><?php _e('Transition Speed', 'responsive-menu-pro'); ?></h4> 

                    <h5><?php _e('Enter a speed in seconds below of the hover transition effect', 'responsive-menu-pro'); ?>. <span class="default"><?php _e('default', 'responsive-menu-pro'); ?>: 1</span></h5>

                    <input 
                        type="text" 
                        name="transition_speed" 
                        class="numberInput" 
                        value="<?php echo isset($data['transition_speed']) ? $data['transition_speed'] : ''; ?>" 
                        /> <?php _e('seconds', 'responsive-menu-pro'); ?>

                </td>
            </tr>
            <tr>
                <td>

                    <h4><?php _e('Accordion Animation For Sub-Menus', 'responsive-menu-pro'); ?></h4> 

                    <h5><?php _e('Tick to enable the accordion animation for sub-menu items', 'responsive-menu-pro'); ?>.</h5>

                    <input 
                        type="checkbox" 
                        name="use_accordion" 
                        id="use_accordion"
                        value="accordion"
                        <?php echo isset($data['use_accordion']) && $data['use_accordion'] == 'accordion' ? ' checked="checked" ' : ''; ?>
                        />

                </td>
                <td>

                    <h4><?php _e('Push button with Animation', 'responsive-menu-pro'); ?></h4> 

                    <h5><?php _e('Tick to enable the click button to be pushed with animation', 'responsive-menu-pro'); ?>.</h5>

                    <input 
                        type="checkbox" 
                        name="use_push_animation" 
                        id="use_push_animation"
                        value="use_push_animation"
                        <?php echo isset($data['use_push_animation']) && $data['use_push_animation'] == 'use_push_animation' ? ' checked="checked" ' : ''; ?>
                        />


                </td>
            </tr>

        </table>



        <h3><?php _e('Additional HTML Content Settings', 'responsive-menu-pro'); ?></h3>

        <table>

            <tr>
                <td>

                    <h4><?php _e('Additional HTML Content', 'responsive-menu-pro'); ?></h4> 

                    <h5><?php _e('Enter any additional HTML you may want below, useful for advertisement banners etc. (accepts shortcodes)', 'responsive-menu-pro'); ?></h5>

                    <textarea name="html"><?php echo isset($data['html']) ? $data['html'] : ''; ?></textarea>

                </td>
                <td>

                    <h4><?php _e('Additional HTML Content Positioning', 'responsive-menu-pro'); ?></h4> 

                    <h5><?php _e('Select where you would like the additional HTML content to appear', 'responsive-menu-pro'); ?></h5>

                    <select name="html_location">

                        <option 
                            value="above"
                            <?php echo isset($data['html_location']) && 'above' == $data['html_location'] ? ' selected="selected " ' : ''; ?>>
                                <?php _e('Above Menu Links', 'responsive-menu-pro'); ?>
                        </option>
                        <option 
                            value="below"
                            <?php echo isset($data['html_location']) && 'below' == $data['html_location'] ? ' selected="selected " ' : ''; ?>>
                                <?php _e('Below Menu Links', 'responsive-menu-pro'); ?>
                        </option>  

                    </select>

                </td>
            </tr>

        </table>

    </div>

    <div class="advanced-setting">
        <h3><?php _e('Menu Advanced Settings', 'responsive-menu-pro'); ?></h4>

            <table>
                <tr>
                    <td>

                        <h4><?php _e('Menu Breakpoint', 'responsive-menu-pro'); ?></h4> 

                        <h5><?php _e('This is the point where the responsive menu will be visible in px width of the browser', 'responsive-menu-pro'); ?></h5>

                        <input 
                            class="numberInput" 
                            type="text" 
                            name="breakpoint" 
                            value="<?php echo isset($data['breakpoint']) ? $data['breakpoint'] : ''; ?>" 
                            /> <?php _e('px', 'responsive-menu-pro'); ?>

                    </td>
                    <td>

                        <h4><?php _e('CSS of Menu To Hide', 'responsive-menu-pro'); ?></h4> 

                        <h5><?php _e('This is the CSS of the menu you want to hide once the responsive menu shows', 'responsive-menu-pro'); ?> - <?php _e('e.g', 'responsive-menu-pro'); ?> #primary-nav, .menu</h5>

                        <input 
                            type="text" 
                            name="css" 
                            value="<?php echo isset($data['css']) ? $data['css'] : ''; ?>" 
                            />

                    </td>
                </tr>

                <tr>
                    <td>

                        <h4><?php _e('Menu Depth', 'responsive-menu-pro'); ?></h4> 

                        <h5><?php _e('This is how deep into your menu tree will be visible (max', 'responsive-menu-pro'); ?>5)</h5>

                        <select name="depth">

                            <?php for ($i = 1; $i < 6; $i++) : ?>

                                <option 
                                    value="<?php echo $i; ?>"
                                    <?php echo isset($data['depth']) && $i == $data['depth'] ? 'selected="selected"' : ''; ?>>
                                        <?php echo $i; ?>
                                </option>

                            <?php endfor; ?>

                        </select>

                    </td>
                    <td>

                        <h4><?php _e('Menu Width', 'responsive-menu-pro'); ?></h4> 

                        <h5><?php _e('This is the width the menu takes up across the page once expanded', 'responsive-menu-pro'); ?>. 
                            <span class="default"><?php _e('default', 'responsive-menu-pro'); ?>: 75</span>
                        </h5>

                        <input 
                            class="numberInput" 
                            type="text" 
                            name="width" 
                            value="<?php echo isset($data['width']) ? $data['width'] : ''; ?>" 
                            /> %

                    </td>
                </tr> 
                <tr>
                    <td>

                        <h4><?php _e('Word Wrap', 'responsive-menu-pro'); ?></h4> 

                        <h5><?php _e('Tick if you would like the link items to wrap around', 'responsive-menu-pro'); ?></h5>

                        <input 
                            type="checkbox" 
                            name="word_wrap"
                            value="word_wrap"
                            <?php echo isset($data['word_wrap']) && $data['word_wrap'] == 'word_wrap' ? ' checked="checked" ' : ''; ?>
                            />

                    </td>
                   <td></td>
                  </tr>
                 </table>
                 

            <table>
                <tr>
                    <td>

                        <h4><?php _e('Remove Search Box', 'responsive-menu-pro'); ?></h4> 

                        <h5><?php _e('Tick if you would like to remove the search box', 'responsive-menu-pro'); ?></h5>

                        <input 
                            type="checkbox" 
                            name="include_search"
                            value="search"
                            <?php echo isset($data['include_search']) && $data['include_search'] == 'search' ? ' checked="checked" ' : ''; ?>
                            />

                    </td>
                    <td>

                        <h4><?php _e('Search Box Positioning', 'responsive-menu-pro'); ?></h4> 

                        <h5><?php _e('Select where you would like the search box to appear', 'responsive-menu-pro'); ?></h5>

                        <select name="search_position">

                            <option 
                                value="above"
                                <?php echo isset($data['search_position']) && 'above' == $data['search_position'] ? ' selected="selected " ' : ''; ?>>
                                    <?php _e('Above Menu Links', 'responsive-menu-pro'); ?>
                            </option>
                            <option 
                                value="below"
                                <?php echo isset($data['search_position']) && 'below' == $data['search_position'] ? ' selected="selected " ' : ''; ?>>
                                    <?php _e('Below Menu Links', 'responsive-menu-pro'); ?>
                            </option>  

                        </select>

                    </td>                
                </tr>  
                <tr>
                    <td>

                        <h4><?php _e('Search Box Text', 'responsive-menu-pro'); ?></h4> 

                        <h5><?php _e('This is the placeholder text that shows in the search box', 'responsive-menu-pro'); ?></h5>

                        <input 
                            type="text" 
                            name="search_text" 
                            value="<?php echo isset($data['search_text']) ? $data['search_text'] : ''; ?>" 
                            />


                    </td>
                    <td>

                    </td>                
                </tr>  



                <tr>
                    <td>
                        <h4><?php _e('Click to Close Menu on Link Click', 'responsive-menu-pro'); ?></h4> 

                        <h5><?php _e('Tick if you would like to close the menu on each link click, useful for single page sites', 'responsive-menu-pro'); ?></h5>

                        <input 
                            type="checkbox" 
                            name="close_on_link_click"
                            value="close"
                            <?php echo isset($data['close_on_link_click']) && $data['close_on_link_click'] == 'close' ? ' checked="checked" ' : ''; ?>
                            />


                    </td>
                    <td>
                        <h4><?php _e('Auto Expand Current Parent Items', 'responsive-menu-pro'); ?></h4> 

                        <h5><?php _e('Tick if you would like to make the current pages children expanded automatically', 'responsive-menu-pro'); ?></h5>

                        <input 
                            type="checkbox" 
                            name="expand_parents"
                            value="expand"
                            <?php echo isset($data['expand_parents']) && $data['expand_parents'] == 'expand' ? ' checked="checked" ' : ''; ?>
                            />
                    </td>                
                </tr>  

                <tr>
                    <td>
                        <h4><?php _e('Auto Expand Sub-Menus', 'responsive-menu-pro'); ?></h4> 

                        <h5><?php _e('Tick if you would like sub-menus to be automatically expanded', 'responsive-menu-pro'); ?></h5>

                        <input 
                            type="checkbox" 
                            name="auto_expand_submenus" 
                            id="auto_expand_submenus"
                            value="expand"
                            <?php echo isset($data['auto_expand_submenus']) && $data['auto_expand_submenus'] == 'expand' ? ' checked="checked" ' : ''; ?>
                            />


                    </td>
                    <td>
                        <h4><?php _e('Ignore Parent Clicks', 'responsive-menu-pro'); ?></h4> 

                        <h5><?php _e('Tick if you would like to ignore clicks on parent links', 'responsive-menu-pro'); ?></h5>

                        <input 
                            type="checkbox" 
                            name="ignore_parent_clicks"
                            value="ignoreparentclick"
                            <?php echo isset($data['ignore_parent_clicks']) && $data['ignore_parent_clicks'] == 'ignoreparentclick' ? ' checked="checked" ' : ''; ?>
                            />
                    </td>                
                </tr>  

                <tr>
                    <td>
                        <h4><?php _e('Click to Close Menu on Page Click', 'responsive-menu-pro'); ?></h4> 

                        <h5><?php _e('Tick if you would like to close the current menu on page clicks', 'responsive-menu-pro'); ?></h5>

                        <input 
                            type="checkbox" 
                            name="click_to_close" 
                            value="clicktoclose"
                            <?php echo isset($data['click_to_close']) && $data['click_to_close'] == 'clicktoclose' ? ' checked="checked" ' : ''; ?>
                            />


                    </td>
                    <td>
                    	
                        <h4><?php _e('Disable background scrolling when Menu is active', 'responsive-menu-pro'); ?></h4> 

                        <h5><?php _e('This will create a background overlay and disable scrolling', 'responsive-menu-pro'); ?></h5>

                        <input 
                            type="checkbox" 
                            name="disable_scrolling"
                            value="disable_scrolling"
                            <?php echo isset($data['disable_scrolling']) && $data['disable_scrolling'] == 'disable_scrolling' ? ' checked="checked" ' : ''; ?>
                            />

                    </td>                
                </tr>  

            </table>

            <h3><?php _e('Technical Settings', 'responsive-menu-pro'); ?></h3>

            <table>
                <tr>
                    <td>

                        <h4><?php _e('Minify output', 'responsive-menu-pro'); ?></h4> 

                        <h5><?php _e('Tick if you would like to minify the script/style output. Saves up to 50% in file size', 'responsive-menu-pro'); ?></h5>

                        <input 
                            type="checkbox" 
                            name="minify"
                            value="minify"
                            <?php echo isset($data['minify']) && $data['minify'] == 'minify' ? ' checked="checked" ' : ''; ?>
                            />

                    </td>
                    <td>

                        <h4><?php _e('Include script in footer', 'responsive-menu-pro'); ?></h4> 

                        <h5><?php _e('Tick if you would like to include your jQuery script in footer', 'responsive-menu-pro'); ?></h5>

                        <input 
                            type="checkbox" 
                            name="scripts_in_footer" 
                            id="scripts_in_footer"
                            value="footer"
                            <?php echo isset($data['scripts_in_footer']) && $data['scripts_in_footer'] == 'footer' ? ' checked="checked" ' : ''; ?>
                            />

                    </td>
                </tr>
                <tr>
                    <td>
                        <h4><?php _e('Include CSS/JS as external files', 'responsive-menu-pro'); ?></h4> 

                        <h5><?php _e('Tick if you would like to include CSS and jQuery as external files', 'responsive-menu-pro'); ?></h5>

                        <input 
                            type="checkbox" 
                            name="create_external_scripts" 
                            id="create_external_scripts"
                            value="external"
                            <?php echo isset($data['create_external_scripts']) && $data['create_external_scripts'] == 'external' ? ' checked="checked" ' : ''; ?>
                            />
                    </td>
                    <td>
                        <h4><?php _e('Remove CSS !important tags', 'responsive-menu-pro'); ?></h4> 

                        <h5>
                            <?php _e('Tick this if you would like to remove the !important tags from the CSS', 'responsive-menu-pro'); ?>. 
                            <?php _e('Ticking this will make it easier to over-ride the styles but may make the default settings not display well', 'responsive-menu-pro'); ?>
                        </h5>
                        <input 
                            type="checkbox" 
                            name="remove_important" 
                            id="remove_important"
                            value="remove"
                            <?php echo $data['remove_important'] == 'remove' ? ' checked="checked" ' : ''; ?>
                            />
                    </td>
                </tr>

            </table>

            <h3><?php _e('Custom Walker', 'responsive-menu-pro'); ?></h3>

            <table>

                <!-- Add by Mkdgs -->
                <tr>
                    <td>    

                        <h4><?php _e('Specify you own Walker for the menu (wp_nav_menu parameter)', 'responsive-menu-pro'); ?></h4>
                        <h5><?php _e('For advanced users only - if you don\'t know what you\'re doing please leave alone', 'responsive-menu-pro'); ?></h5>

                        <input name="walker" type="text"
                               value="<?php echo isset($data['walker']) ? $data['walker'] : ''; ?>" />

                    </td>

                    <td>

                    </td>
                </tr>

            </table>
    </div>
    
    <div class="import-export">	
    	
        <h3>Import Options</h3>

        <table>

            <tr>

                <td>
                    <br />

                    <input
                        type="file" 
                        class="button file" 
                        name="responsive_menu_pro_import_file" 
                        value="<?php _e('Import File', 'responsive-menu-pro'); ?>"
                        />

                    <input 
                        type="submit" 
                        class="button" 
                        name="responsive_menu_pro_import" 
                        value="<?php _e('Import Options From XML', 'responsive-menu-pro'); ?>"
                        />
                </td>

            </tr>

        </table>
                
        <h3>Export Options</h3>

        <table>

            <tr>
                <td>
                	<br />
                    <input 
                        type="submit" 
                        class="button" 
                        name="responsive_menu_pro_export" 
                        value="<?php _e('Export Current Options', 'responsive-menu-pro'); ?>"
                        />
                </td>
            </tr>
        </table>

        <h3>Reset to defaults</h3>

        <table>

            <tr>

				<td>
                    <h4 class="divider">
                        <?php _e('Note'); ?>: 
                        <?php _e('Please be warned this will reset all your current settings, please export your current files first', 'responsive-menu-pro'); ?>.
                    </h4>
                    <input 
                        type="submit" 
                        class="button" 
                        name="responsive_menu_pro_reset" 
                        value="<?php _e('Reset ALL Current Options', 'responsive-menu-pro' ); ?>"
                        />
					
					
                </td>

            </tr>

        </table>
        
    </div>
    
    <div class="single-menu">
    	
            <h3><?php _e('Use Responsive Menu as your only site menu', 'responsive-menu-pro'); ?></h3>

            <table>

                <tr>
                    <td>
                        <h4>
                            <?php _e('Turn on single menu option', 'responsive-menu-pro'); ?>
                        </h4> 
                        <h5>
                            <?php _e('This will replace your whole site menu and just use this plugin to control the menu on your whole site.', 'responsive-menu-pro'); ?>
	                        <h4 class="divider">
	                            <?php _e('Note', 'responsive-menu-pro'); ?>: 
	                            <?php _e('You must not be using the mobile only option and must use the shortcode for this to work', 'responsive-menu-pro'); ?>.
	                        </h4>
                        </h5> 

                        <input 
                            type="checkbox" 
                            name="use_single_site_menu" 
                            value="use_single_site_menu"
                            <?php echo isset($data['use_single_site_menu']) && $data['use_single_site_menu'] == 'use_single_site_menu' ? ' checked="checked" ' : ''; ?>
                            />

                    </td>
                </tr>
                <tr>
                <td>                    

                    <h4><?php _e('Menu Height', 'responsive-menu-pro'); ?></h4> 

                    <h5><?php _e('Enter the height you wish for the menu and links', 'responsive-menu-pro'); ?>.</h5>

                    <input 
                        type="text" 
                        name="single_menu_height" 
                        class="numberInput" 
                        value="<?php echo isset($data['single_menu_height']) ? $data['single_menu_height'] : ''; ?>" 
                        /> <?php _e('px', 'responsive-menu-pro'); ?>

                </td>
                <td></td>
                </tr>
                <tr>
	                <td>
	                	
	                	<h4><?php _e('Single Menu Link Colour', 'responsive-menu-pro'); ?></h4> 
	
	                    <h5><?php _e('This is the colour of the single menu links', 'responsive-menu-pro'); ?></h5>
	
	                    <input 
	                        type="text" 
	                        name="single_menu_link_colour"
	                        class="colourPicker" 
	                        value="<?php echo isset($data['single_menu_link_colour']) ? $data['single_menu_link_colour'] : ''; ?>" 
	                        />
	                </td>
	                <td>
	                	
	                	<h4><?php _e('Single Menu Link Hover Colour', 'responsive-menu-pro'); ?></h4> 
	
	                    <h5><?php _e('This is the hover colour of the single menu links', 'responsive-menu-pro'); ?></h5>
	
	                    <input 
	                        type="text" 
	                        name="single_menu_link_colour_hover"
	                        class="colourPicker" 
	                        value="<?php echo isset($data['single_menu_link_colour_hover']) ? $data['single_menu_link_colour_hover'] : ''; ?>" 
	                        />
	                </td>
               </tr>
            </table>

	</div>

    <div class="themes">
    
        <h3><?php _e( 'Header Bar', 'responsive-menu-pro' ); ?></h3>
    
        <table>

            <tr>
                <td>
                    <h4>
                        <?php _e( 'Create header bar for use with Responsive Menu', 'responsive-menu-pro' ); ?>
                    </h4> 
                    <h5>
                        <?php _e('This will create a sticky header bar that follows you down the page with the menu and logo', 'responsive-menu-pro'); ?>
                    </h5> 

                    <input 
                        type="checkbox" 
                        name="use_header_bar" 
                        value="use_header_bar"
                        <?php echo isset($data['use_header_bar']) && $data['use_header_bar'] == 'use_header_bar' ? ' checked="checked" ' : ''; ?>
                        />

                </td>
            </tr>
            
            <tr>
                <td><h4><?php _e( 'Header Bar Logo/HTML' ); ?></h4></td>
            </tr>
            <tr>
                <td>
                    <h4><?php _e('Header Bar Logo', 'responsive-menu-pro'); ?></h4> 

                    <h5><?php _e('This is the header bar logo that is displayed on the bar', 'responsive-menu-pro'); ?></h5>

                    <input 
                        type="text" 
                        id="header_bar_logo" 
                        name="header_bar_logo" 
                        value="<?php echo isset($data['header_bar_logo']) ? $data['header_bar_logo'] : ''; ?>" 
                        />

                    <input 
                        type="button"
                        value="<?php _e('Upload Image', 'responsive-menu-pro'); ?>" 
                        class="button RMImageButton" 
                        for="header_bar_logo"
                        />

                </td>
                
                <td>
                    <h4><?php _e('Header Bar HTML Content', 'responsive-menu-pro'); ?></h4> 

                    <h5><?php _e('You can set HTML in the header bar instead of the logo', 'responsive-menu-pro'); ?></h5>

                    <textarea name="header_bar_html"><?php echo isset($data['header_bar_html']) ? $data['header_bar_html'] : ''; ?></textarea>

                </td>
                
            </tr>

            <tr>
                <td>

                    <h4><?php _e('Header Bar Logo Link', 'responsive-menu-pro'); ?></h4> 

                    <h5><?php _e('This is the header bar logo link', 'responsive-menu-pro'); ?></h5>

                    <input 
                        type="text" 
                        id="header_bar_logo_link" 
                        name="header_bar_logo_link" 
                        value="<?php echo isset($data['header_bar_logo_link']) ? $data['header_bar_logo_link'] : ''; ?>" 
                        />

                </td>
                <td>
                </td>
            </tr>
                
            <tr>
                <td><h4><?php _e( 'Size & Colour Settings', 'responsive-menu-pro' ); ?></h4></td>
            </tr>
            <tr>
                <td>
                    
                    <h4><?php _e('Header Bar Height', 'responsive-menu-pro'); ?></h4> 
                    <h5><?php _e('This is the header bar height', 'responsive-menu-pro'); ?></h5>

                    <input 
                        type="text"
                        name="header_bar_height" 
                        value="<?php echo isset($data['header_bar_height']) ? $data['header_bar_height'] : ''; ?>" 
                        /> px

                </td>
                
                <td>
                    <h4><?php _e('Header Bar Background Colour', 'responsive-menu-pro'); ?></h4> 

                    <h5><?php _e('This is the background colour for the header bar', 'responsive-menu-pro'); ?></h5>

                    <input 
                        type="text" 
                        name="header_bar_background_colour"
                        class="colourPicker" 
                        value="<?php echo isset($data['header_bar_background_colour']) ? $data['header_bar_background_colour'] : ''; ?>" 
                        />

                </td>
                
            </tr>          

            <tr>
                <td><h4><?php _e( 'Header Search Settings', 'responsive-menu-pro' ); ?></h4></td>
            </tr>
            <tr>
                <td>
                    
                    <h4><?php _e('Include Search in Header', 'responsive-menu-pro'); ?></h4> 
                    <h5><?php _e('This will include the search bar in the header', 'responsive-menu-pro'); ?></h5>

                    <input 
                            type="checkbox" 
                            name="include_header_search"
                            value="include_header_search"
                            <?php echo isset($data['include_header_search']) && $data['include_header_search'] == 'include_header_search' ? ' checked="checked" ' : ''; ?>
                            />

                </td>
                
                <td>
                    <h4><?php _e('Header Search Location', 'responsive-menu-pro'); ?></h4> 

                    <h5><?php _e('This is where the header search will be included in your header bar', 'responsive-menu-pro'); ?></h5>

                        <select name="header_search_position">

                            <option 
                                value="before_logo"
                                <?php echo 'before_logo' == $data['header_search_position'] ? 'selected="selected"' : ''; ?>>
                                Before Logo
                            </option>

                            <option 
                                value="after_logo"
                                <?php echo 'after_logo' == $data['header_search_position'] ? 'selected="selected"' : ''; ?>>
                                After Logo
                            </option>

                        </select>

                </td>
                
            </tr>
                                        
        </table>        

        <h3><?php _e( 'Themes', 'responsive-menu-pro' ); ?></h3>
        
        <table>

            <tr>
                <td>
                    <h4>
                        <?php _e( 'Apply preset colour schemes to your Responsive Menu', 'responsive-menu-pro' ); ?>
                    </h4> 
                    <h5>
                        <?php _e('This will replace all your current colours only and will not touch other settings', 'responsive-menu-pro'); ?>
                    </h5> 

                    <select name="theme">
                        <option value="blue">Blue</option>
                        <option value="red">Red</option>
                        <option value="green">Green</option>
                        <option value="yellow">Yellow</option>
                        <option value="default">Default</option>
                    </select>
                    
                    <input 
                        type="submit" 
                        class="button"
                        name="responsive_menu_pro_update_theme" 
                        value="Update Theme"
                        />

                </td>
            </tr>
                
        </table>    
                
    </div>	

    <div class="custom-css">
	
		<h3><?php _e( 'Custom CSS/HTML', 'responsive-menu-pro' ); ?></h3>
	
		<table>

       
            <tr>
                
                <td>
                    <h4><?php _e('Custom CSS', 'responsive-menu-pro'); ?></h4> 

                    <h5><?php _e('These will be the final CSS rules applied to the Responsive Menu and are upgrade proof', 'responsive-menu-pro'); ?></h5>

                    <textarea rows="15" name="custom_css"><?php echo isset($data['custom_css']) ? $data['custom_css'] : ''; ?></textarea>

                </td>
                
            </tr>
                
		</table>	
				
	</div>
	
    <br /><br />

    <input 
        type="submit" 
        class="button button-primary" 
        name="responsive_menu_pro_submit" 
        value="<?php _e('Update Responsive Menu Options', 'responsive-menu-pro'); ?>"
        />



</form>

</div>
